"""
Writing voice profile — a personal description of how one person writes.

Gerry reads this before drafting an email so the words come out sounding like
the person whose name is on them: their rhythm, their openers, the way they say
no, how long their sentences run. The profile is generated by reading the user's
own sent mail and describing it the way a speaking coach would, or it can simply
be pasted in as markdown.

It is scoped to a single user on purpose. A voice profile describes one
individual, so it lives on ``users.writing_voice_profile`` rather than in
``system_settings`` (which every account on the install shares). Emails always
use it; other writing only does so when the user turns that on.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone

from sqlalchemy.ext.asyncio import AsyncSession

from models.db.user import User

logger = logging.getLogger(__name__)

# Big enough for a genuinely detailed profile, small enough that injecting it on
# every draft does not crowd out the email itself.
MAX_PROFILE_CHARS = 16_000

# How much sent mail to read, and how much of each message.
SENT_QUERY = "in:sent newer_than:180d"
MAX_SENT_MESSAGES = 120
BATCH_SIZE = 20
MAX_BODY_CHARS = 2_000


# ── Read / write ──────────────────────────────────────────────────────────────

async def get_profile(db: AsyncSession, user_id) -> str:
    """The raw markdown profile for a user, or "" if they have none."""
    user = await db.get(User, user_id)
    return (user.writing_voice_profile or "").strip() if user else ""


async def set_profile(
    db: AsyncSession,
    user_id,
    profile: str | None,
    *,
    for_documents: bool | None = None,
) -> User | None:
    """Save (or clear) a user's profile. Returns the updated user."""
    user = await db.get(User, user_id)
    if user is None:
        return None
    if profile is not None:
        cleaned = profile.strip()[:MAX_PROFILE_CHARS]
        user.writing_voice_profile = cleaned or None
        user.writing_voice_updated_at = datetime.now(timezone.utc) if cleaned else None
    if for_documents is not None:
        user.writing_voice_for_documents = bool(for_documents)
    await db.flush()
    return user


# ── Prompt injection ──────────────────────────────────────────────────────────

def style_block(profile: str) -> str:
    """Format a profile for injection into a drafting prompt."""
    profile = (profile or "").strip()
    if not profile:
        return ""
    return (
        "\n\n# HOW THIS PERSON WRITES\n"
        "The draft goes out under their name, so match the voice described below — "
        "sentence length, openers, sign-offs, level of directness, and vocabulary. "
        "Never mention this description or that you are imitating anyone. Facts and "
        "the requested content still come first; voice is how you say it, not what "
        "you say.\n\n"
        f"{profile[:MAX_PROFILE_CHARS]}\n"
    )


async def get_style_block(db: AsyncSession, user_id, *, for_documents: bool = False) -> str:
    """Style block for a user, or "" when they have no profile.

    ``for_documents=True`` is used for non-email writing, which only picks up the
    voice when the user has explicitly opted in.
    """
    if user_id is None:
        return ""
    user = await db.get(User, user_id)
    if user is None or not user.writing_voice_profile:
        return ""
    if for_documents and not user.writing_voice_for_documents:
        return ""
    return style_block(user.writing_voice_profile)


async def get_email_style_block(db: AsyncSession, user_id) -> str:
    """Convenience wrapper — emails always use the profile when one exists."""
    return await get_style_block(db, user_id, for_documents=False)


async def get_agent_style_block(db: AsyncSession, user_id) -> str:
    """Style block for the chat agent's system prompt.

    The agent writes emails *and* everything else, so the scope is spelled out
    in the prompt rather than decided here: emails always adopt the voice, other
    writing only if the user opted in.
    """
    if user_id is None:
        return ""
    user = await db.get(User, user_id)
    if user is None or not user.writing_voice_profile:
        return ""
    scope = (
        "Use this voice for everything you write on the user's behalf — emails, "
        "documents, summaries and messages."
        if user.writing_voice_for_documents
        else "Use this voice when you draft emails or messages the user will send "
        "under their own name. Reports, regulatory documents and other formal "
        "deliverables keep their normal house style."
    )
    return style_block(user.writing_voice_profile) + f"\n{scope}\n"


# ── Analysis ──────────────────────────────────────────────────────────────────

_QUOTE_LINE = re.compile(r"^\s*(>|On .{0,80}wrote:)", re.MULTILINE)


def _strip_quoted(body: str) -> str:
    """Drop quoted history so the analysis reads what the user actually typed."""
    body = body.replace("\r\n", "\n")
    for marker in ("\n-----Original Message-----", "\n________________________________"):
        idx = body.find(marker)
        if idx > 0:
            body = body[:idx]
    lines: list[str] = []
    for line in body.split("\n"):
        if _QUOTE_LINE.match(line):
            break
        lines.append(line)
    return "\n".join(lines).strip()


def _collect_sent(max_messages: int) -> list[dict]:
    """Fetch the user's recent sent mail with bodies. Runs blocking Google calls."""
    from services import google_service as gs

    headers = gs.gmail_search(SENT_QUERY, max_results=max_messages)
    out: list[dict] = []
    for h in headers:
        try:
            full = gs.gmail_get_message(h["id"])
        except Exception:  # one unreadable message must not sink the analysis
            continue
        body = _strip_quoted(full.get("body", ""))
        if len(body) < 40:  # one-liners teach nothing about cadence
            continue
        out.append({
            "to": full.get("to", ""),
            "subject": full.get("subject", ""),
            "date": full.get("date", ""),
            "body": body[:MAX_BODY_CHARS],
        })
    return out


def _format_batch(batch: list[dict]) -> str:
    return "\n\n---\n\n".join(
        f"To: {m['to']}\nSubject: {m['subject']}\nDate: {m['date']}\n\n{m['body']}"
        for m in batch
    )


_BATCH_PROMPT = (
    "Below are real emails written by one person. Study them the way a speaking "
    "coach studies a client: what is characteristic, not what is generic.\n\n"
    "Write terse observational notes covering: typical opening and closing lines; "
    "sentence length and rhythm; punctuation habits (dashes, ellipses, exclamation "
    "marks, paragraph length); vocabulary and recurring phrases; how directness and "
    "warmth change depending on who they are writing to; how they ask for things, "
    "push back, apologise, and deliver bad news; use of humour; formatting habits "
    "(bullets, bold, greetings, sign-offs); anything they conspicuously never do.\n\n"
    "Quote short characteristic fragments as evidence. Do not summarise the "
    "content of the emails — describe the writing.\n\nEMAILS:\n{batch}"
)

_SYNTHESIS_PROMPT = (
    "You are a speaking and writing coach. Below are your own observation notes "
    "from reading one person's emails. Write the finished voice profile for that "
    "person: a detailed, specific portrait another writer could use to produce a "
    "message indistinguishable from theirs.\n\n"
    "Return markdown with exactly these sections:\n"
    "# Writing Voice Profile\n"
    "## At a glance — three or four sentences capturing the overall impression.\n"
    "## Voice and personality — what their writing says about how they think and "
    "how they treat people.\n"
    "## Cadence and structure — sentence length, paragraph shape, rhythm, pacing.\n"
    "## Vocabulary and signature phrases — words and constructions they reach for, "
    "with real examples.\n"
    "## Punctuation and formatting habits.\n"
    "## Openers and sign-offs — what they actually use, and when each one appears.\n"
    "## Register by audience — how the voice shifts for colleagues, customers, "
    "vendors, executives, and people they do not know.\n"
    "## Behavioural patterns — asking, refusing, escalating, apologising, chasing, "
    "delivering bad news, giving praise.\n"
    "## What this person never does — the anti-patterns that would break the voice.\n"
    "## Quick checklist for drafting in this voice — six to ten imperative bullets.\n\n"
    "Be concrete and specific. Prefer observed detail over flattery, and say so "
    "plainly where the evidence was thin.\n\nOBSERVATION NOTES:\n{notes}"
)


async def analyze_sent_mail(
    db: AsyncSession,
    *,
    max_messages: int = MAX_SENT_MESSAGES,
) -> tuple[str, int]:
    """Read the connected account's sent mail and write a voice profile.

    Returns ``(markdown_profile, messages_analysed)``. Raises ``ValueError`` when
    there is not enough sent mail to say anything honest about.
    """
    import asyncio

    from services.llm.router import get_llm_client

    messages = await asyncio.to_thread(_collect_sent, max_messages)
    if len(messages) < 5:
        raise ValueError(
            "I could only find "
            f"{len(messages)} substantial sent email(s) from the last six months — "
            "not enough to describe how you write. Send a few more, or paste a "
            "profile in by hand."
        )

    client = await get_llm_client(db, task="emails")

    notes: list[str] = []
    for start in range(0, len(messages), BATCH_SIZE):
        batch = messages[start:start + BATCH_SIZE]
        chunk = await client.chat(
            messages=[{"role": "user", "content": _BATCH_PROMPT.format(batch=_format_batch(batch))}],
            temperature=0.3,
        )
        notes.append(chunk.content.strip())

    final = await client.chat(
        messages=[{"role": "user", "content": _SYNTHESIS_PROMPT.format(notes="\n\n".join(notes))}],
        temperature=0.4,
    )
    profile = final.content.strip()[:MAX_PROFILE_CHARS]
    logger.info("Built writing voice profile from %d sent emails", len(messages))
    return profile, len(messages)
