"""add_missing_columns

Revision ID: 615f52d537b5
Revises: 001
Create Date: 2026-06-02 09:49:48.649644

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '615f52d537b5'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('agent_runs', sa.Column('input_text', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('output_text', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('agent_runs', sa.Column('model_provider', sa.String(length=50), nullable=True))
    op.alter_column('agent_runs', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('agent_runs', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_agent_runs_user_id_users'), 'agent_runs', 'users', ['user_id'], ['id'])
    op.add_column('approval_intents', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('approval_intents', sa.Column('intent_type', sa.String(length=50), nullable=False))
    op.add_column('approval_intents', sa.Column('intent_title', sa.String(length=500), nullable=False))
    op.add_column('approval_intents', sa.Column('intent_description', sa.Text(), nullable=True))
    op.alter_column('approval_intents', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_approval_intents_status'), table_name='approval_intents')
    op.create_index(op.f('ix_approval_intents_agent_run_id'), 'approval_intents', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_approval_intents_user_id'), 'approval_intents', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_approval_intents_requested_by_id_users'), 'approval_intents', type_='foreignkey')
    op.drop_constraint(op.f('fk_approval_intents_conversation_id_conversations'), 'approval_intents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_approval_intents_user_id_users'), 'approval_intents', 'users', ['user_id'], ['id'])
    op.drop_column('approval_intents', 'description')
    op.drop_column('approval_intents', 'action_type')
    op.drop_column('approval_intents', 'requested_by_id')
    op.drop_column('approval_intents', 'conversation_id')
    op.drop_index(op.f('ix_audit_events_entity'), table_name='audit_events')
    op.drop_constraint(op.f('uq_capas_capa_number'), 'capas', type_='unique')
    op.drop_index(op.f('ix_capas_capa_number'), table_name='capas')
    op.create_index(op.f('ix_capas_capa_number'), 'capas', ['capa_number'], unique=True)
    op.add_column('conversations', sa.Column('agent_type', sa.String(length=50), nullable=True))
    op.add_column('conversations', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.alter_column('document_categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('document_chunks', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.add_column('document_chunks', sa.Column('section_title', sa.Text(), nullable=True))
    op.add_column('document_chunks', sa.Column('parent_chunk_id', sa.UUID(), nullable=True))
    op.add_column('document_chunks', sa.Column('chunk_level', sa.Integer(), nullable=False))
    op.add_column('document_chunks', sa.Column('embedding_model', sa.String(length=100), nullable=False))
    op.add_column('document_chunks', sa.Column('embedding_created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_document_chunks_embedding_ivfflat'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    op.create_foreign_key(op.f('fk_document_chunks_parent_chunk_id_document_chunks'), 'document_chunks', 'document_chunks', ['parent_chunk_id'], ['id'])
    op.drop_column('document_chunks', 'token_count')
    op.add_column('documents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('source_uri', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('source_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('file_name', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('document_date', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('version', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('is_confidential', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('documents', 'source_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'upload'::character varying"))
    op.alter_column('documents', 'mime_type',
               existing_type=sa.VARCHAR(length=127),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.create_index(op.f('ix_documents_category_id'), 'documents', ['category_id'], unique=False)
    op.create_index(op.f('ix_documents_checksum_sha256'), 'documents', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_foreign_key(op.f('fk_documents_deleted_by_users'), 'documents', 'users', ['deleted_by'], ['id'])
    op.drop_column('documents', 'source_url')
    op.drop_column('documents', 'filename')
    op.drop_column('documents', 'file_path_encrypted')
    op.drop_column('documents', 'raw_content')
    op.drop_constraint(op.f('uq_google_sync_state_user_service'), 'google_sync_state', type_='unique')
    op.add_column('messages', sa.Column('agent_type', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('model_provider', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.alter_column('messages', 'cited_chunk_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=False)
    op.create_index(op.f('ix_messages_agent_run_id'), 'messages', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.drop_column('messages', 'model_used')
    op.drop_column('messages', 'token_count')
    op.add_column('projects', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('target_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_projects_created_by_users'), 'projects', 'users', ['created_by'], ['id'])
    op.create_index(op.f('ix_regulatory_documents_doc_number'), 'regulatory_documents', ['doc_number'], unique=False)
    op.create_index(op.f('ix_risk_items_regulatory_doc_id'), 'risk_items', ['regulatory_doc_id'], unique=False)
    op.add_column('task_comments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('task_comments', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_constraint(op.f('uq_user_sessions_token_hash'), 'user_sessions', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_user_sessions_token_hash'), 'user_sessions', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.alter_column('task_comments', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('task_comments', 'updated_at')
    op.drop_index(op.f('ix_risk_items_regulatory_doc_id'), table_name='risk_items')
    op.drop_index(op.f('ix_regulatory_documents_doc_number'), table_name='regulatory_documents')
    op.drop_constraint(op.f('fk_projects_created_by_users'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'created_by')
    op.drop_column('projects', 'is_archived')
    op.drop_column('projects', 'color')
    op.drop_column('projects', 'target_date')
    op.drop_column('projects', 'start_date')
    op.add_column('messages', sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_agent_run_id'), table_name='messages')
    op.alter_column('messages', 'cited_chunk_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=True)
    op.drop_column('messages', 'output_tokens')
    op.drop_column('messages', 'input_tokens')
    op.drop_column('messages', 'model_provider')
    op.drop_column('messages', 'model_name')
    op.drop_column('messages', 'agent_type')
    op.create_unique_constraint(op.f('uq_google_sync_state_user_service'), 'google_sync_state', ['user_id', 'service'], postgresql_nulls_not_distinct=False)
    op.add_column('documents', sa.Column('raw_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_path_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_documents_deleted_by_users'), 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_category_id'), table_name='documents')
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum_sha256'], unique=False)
    op.alter_column('documents', 'mime_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=127),
               existing_nullable=True)
    op.alter_column('documents', 'source_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'upload'::character varying"))
    op.drop_column('documents', 'last_synced_at')
    op.drop_column('documents', 'deleted_by')
    op.drop_column('documents', 'is_confidential')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'document_date')
    op.drop_column('documents', 'author')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'file_name')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'source_id')
    op.drop_column('documents', 'source_uri')
    op.drop_column('documents', 'description')
    op.add_column('document_chunks', sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_document_chunks_parent_chunk_id_document_chunks'), 'document_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.create_index(op.f('ix_document_chunks_embedding_ivfflat'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('document_chunks', 'embedding_created_at')
    op.drop_column('document_chunks', 'embedding_model')
    op.drop_column('document_chunks', 'chunk_level')
    op.drop_column('document_chunks', 'parent_chunk_id')
    op.drop_column('document_chunks', 'section_title')
    op.drop_column('document_chunks', 'content_hash')
    op.alter_column('document_categories', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('conversations', 'is_pinned')
    op.drop_column('conversations', 'agent_type')
    op.drop_index(op.f('ix_capas_capa_number'), table_name='capas')
    op.create_index(op.f('ix_capas_capa_number'), 'capas', ['capa_number'], unique=False)
    op.create_unique_constraint(op.f('uq_capas_capa_number'), 'capas', ['capa_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_audit_events_entity'), 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.add_column('approval_intents', sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('approval_intents', sa.Column('requested_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('approval_intents', sa.Column('action_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('approval_intents', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_approval_intents_user_id_users'), 'approval_intents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_approval_intents_conversation_id_conversations'), 'approval_intents', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('fk_approval_intents_requested_by_id_users'), 'approval_intents', 'users', ['requested_by_id'], ['id'])
    op.drop_index(op.f('ix_approval_intents_user_id'), table_name='approval_intents')
    op.drop_index(op.f('ix_approval_intents_agent_run_id'), table_name='approval_intents')
    op.create_index(op.f('ix_approval_intents_status'), 'approval_intents', ['status'], unique=False)
    op.alter_column('approval_intents', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('approval_intents', 'intent_description')
    op.drop_column('approval_intents', 'intent_title')
    op.drop_column('approval_intents', 'intent_type')
    op.drop_column('approval_intents', 'user_id')
    op.drop_constraint(op.f('fk_agent_runs_user_id_users'), 'agent_runs', type_='foreignkey')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.alter_column('agent_runs', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
    op.alter_column('agent_runs', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('agent_runs', 'model_provider')
    op.drop_column('agent_runs', 'model_name')
    op.drop_column('agent_runs', 'total_tokens')
    op.drop_column('agent_runs', 'duration_ms')
    op.drop_column('agent_runs', 'output_text')
    op.drop_column('agent_runs', 'input_text')
    op.drop_column('agent_runs', 'user_id')
    # ### end Alembic commands ###
